// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    id,
    user_id,
    public_key,
    sign_count,
    transports,
    aaguid,
    age_recipient,
    nickname
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, public_key, sign_count, transports, aaguid, age_recipient, nickname, created_at, last_used_at, deleted_at
`

type CreateCredentialParams struct {
	ID           []byte
	UserID       pgtype.UUID
	PublicKey    []byte
	SignCount    int64
	Transports   []string
	Aaguid       pgtype.UUID
	AgeRecipient string
	Nickname     *string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.PublicKey,
		arg.SignCount,
		arg.Transports,
		arg.Aaguid,
		arg.AgeRecipient,
		arg.Nickname,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.SignCount,
		&i.Transports,
		&i.Aaguid,
		&i.AgeRecipient,
		&i.Nickname,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUserCredentials = `-- name: ListUserCredentials :many
SELECT id, user_id, public_key, sign_count, transports, aaguid, age_recipient, nickname, created_at, last_used_at, deleted_at FROM credentials
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListUserCredentials(ctx context.Context, userID pgtype.UUID) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listUserCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
			&i.Aaguid,
			&i.AgeRecipient,
			&i.Nickname,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredentialUsage = `-- name: UpdateCredentialUsage :exec
UPDATE credentials
SET sign_count = $2,
    last_used_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateCredentialUsageParams struct {
	ID        []byte
	SignCount int64
}

func (q *Queries) UpdateCredentialUsage(ctx context.Context, arg UpdateCredentialUsageParams) error {
	_, err := q.db.Exec(ctx, updateCredentialUsage, arg.ID, arg.SignCount)
	return err
}
