// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditCheckpoint struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Sequence      int64
	ChainHeadHash []byte
	Signature     []byte
	SignedAt      pgtype.Timestamptz
}

type AuditLog struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Sequence      int64
	EventType     string
	Payload       []byte
	PrevEntryHash []byte
	CreatedAt     pgtype.Timestamptz
}

type Contact struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Email           string
	DisplayName     string
	Status          string
	ContactUserID   pgtype.UUID
	AgeRecipient    *string
	FingerprintHash []byte
	InvitedAt       pgtype.Timestamptz
	VerifiedAt      pgtype.Timestamptz
	RemovedAt       pgtype.Timestamptz
}

type Credential struct {
	ID           []byte
	UserID       pgtype.UUID
	PublicKey    []byte
	SignCount    int64
	Transports   []string
	Aaguid       pgtype.UUID
	AgeRecipient string
	Nickname     string
	CreatedAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type EntryRecipient struct {
	EntryID    pgtype.UUID
	ContactID  pgtype.UUID
	AssignedAt pgtype.Timestamptz
}

type Job struct {
	ID          pgtype.UUID
	Type        string
	Payload     []byte
	RunAfter    pgtype.Timestamptz
	Attempts    int32
	MaxAttempts int32
	Status      string
	LockedBy    *string
	LockedAt    pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	LastError   *string
	DedupKey    *string
}

type ReleaseOffset struct {
	UserID         pgtype.UUID
	SoftAfterDays  int32
	FirmAfterDays  int32
	FinalAfterDays int32
	CoolingHours   int32
	FinalHoldHours int32
}

type ReleaseState struct {
	UserID            pgtype.UUID
	State             string
	LastCheckinAt     pgtype.Timestamptz
	StateEnteredAt    pgtype.Timestamptz
	CoolingStartedAt  pgtype.Timestamptz
	FinalHoldUntil    pgtype.Timestamptz
	FalsePositiveFlag bool
}

type User struct {
	ID          pgtype.UUID
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type VaultEntry struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Preview       []byte
	Bundle        []byte
	SortOrder     int32
	SchemaVersion int16
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type WebauthnSession struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	SessionData []byte
	Purpose     string
	ExpiresAt   pgtype.Timestamptz
	ConsumedAt  pgtype.Timestamptz
}
