// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeSession = `-- name: ConsumeSession :one
UPDATE webauthn_sessions
SET consumed_at = now()
WHERE id = $1
  AND purpose = $2
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, session_data, purpose, expires_at, consumed_at
`

type ConsumeSessionParams struct {
	ID      pgtype.UUID
	Purpose string
}

func (q *Queries) ConsumeSession(ctx context.Context, arg ConsumeSessionParams) (WebauthnSession, error) {
	row := q.db.QueryRow(ctx, consumeSession, arg.ID, arg.Purpose)
	var i WebauthnSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionData,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO webauthn_sessions (id, user_id, session_data, purpose, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, session_data, purpose, expires_at, consumed_at
`

type CreateSessionParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	SessionData []byte
	Purpose     string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (WebauthnSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.SessionData,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i WebauthnSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionData,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
