// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vault_entries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVaultEntry = `-- name: CreateVaultEntry :one
INSERT INTO vault_entries (
    id,
    user_id,
    preview,
    bundle,
    sort_order
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, preview, bundle, sort_order, schema_version, created_at, updated_at, deleted_at
`

type CreateVaultEntryParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Preview   []byte
	Bundle    []byte
	SortOrder int32
}

func (q *Queries) CreateVaultEntry(ctx context.Context, arg CreateVaultEntryParams) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, createVaultEntry,
		arg.ID,
		arg.UserID,
		arg.Preview,
		arg.Bundle,
		arg.SortOrder,
	)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preview,
		&i.Bundle,
		&i.SortOrder,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVaultEntry = `-- name: GetVaultEntry :one
SELECT id, user_id, preview, bundle, sort_order, schema_version, created_at, updated_at, deleted_at FROM vault_entries
WHERE id = $1 AND user_id = $2
`

type GetVaultEntryParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetVaultEntry(ctx context.Context, arg GetVaultEntryParams) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, getVaultEntry, arg.ID, arg.UserID)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preview,
		&i.Bundle,
		&i.SortOrder,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUserVaultEntries = `-- name: ListUserVaultEntries :many
SELECT id, user_id, preview, sort_order, schema_version, created_at, updated_at, deleted_at
FROM vault_entries
WHERE user_id = $1
  AND ($2::boolean OR deleted_at IS NULL)
ORDER BY sort_order ASC, created_at ASC
LIMIT $3
`

type ListUserVaultEntriesParams struct {
	UserID         pgtype.UUID
	IncludeDeleted bool
	RowLimit       int32
}

type ListUserVaultEntriesRow struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Preview       []byte
	SortOrder     int32
	SchemaVersion int16
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) ListUserVaultEntries(ctx context.Context, arg ListUserVaultEntriesParams) ([]ListUserVaultEntriesRow, error) {
	rows, err := q.db.Query(ctx, listUserVaultEntries, arg.UserID, arg.IncludeDeleted, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserVaultEntriesRow{}
	for rows.Next() {
		var i ListUserVaultEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Preview,
			&i.SortOrder,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreVaultEntry = `-- name: RestoreVaultEntry :one
UPDATE vault_entries
SET deleted_at = NULL,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NOT NULL
  AND deleted_at > now() - INTERVAL '30 days'
RETURNING id, user_id, preview, bundle, sort_order, schema_version, created_at, updated_at, deleted_at
`

type RestoreVaultEntryParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RestoreVaultEntry(ctx context.Context, arg RestoreVaultEntryParams) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, restoreVaultEntry, arg.ID, arg.UserID)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preview,
		&i.Bundle,
		&i.SortOrder,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteVaultEntry = `-- name: SoftDeleteVaultEntry :one
UPDATE vault_entries
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, preview, bundle, sort_order, schema_version, created_at, updated_at, deleted_at
`

type SoftDeleteVaultEntryParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) SoftDeleteVaultEntry(ctx context.Context, arg SoftDeleteVaultEntryParams) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, softDeleteVaultEntry, arg.ID, arg.UserID)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preview,
		&i.Bundle,
		&i.SortOrder,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateVaultEntry = `-- name: UpdateVaultEntry :one
UPDATE vault_entries
SET preview = $3,
    bundle = $4,
    sort_order = $5,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, preview, bundle, sort_order, schema_version, created_at, updated_at, deleted_at
`

type UpdateVaultEntryParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Preview   []byte
	Bundle    []byte
	SortOrder int32
}

func (q *Queries) UpdateVaultEntry(ctx context.Context, arg UpdateVaultEntryParams) (VaultEntry, error) {
	row := q.db.QueryRow(ctx, updateVaultEntry,
		arg.ID,
		arg.UserID,
		arg.Preview,
		arg.Bundle,
		arg.SortOrder,
	)
	var i VaultEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Preview,
		&i.Bundle,
		&i.SortOrder,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateVaultEntrySortOrder = `-- name: UpdateVaultEntrySortOrder :exec
UPDATE vault_entries
SET sort_order = $3
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type UpdateVaultEntrySortOrderParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	SortOrder int32
}

func (q *Queries) UpdateVaultEntrySortOrder(ctx context.Context, arg UpdateVaultEntrySortOrderParams) error {
	_, err := q.db.Exec(ctx, updateVaultEntrySortOrder, arg.ID, arg.UserID, arg.SortOrder)
	return err
}
